### ISSUE TITLE
Daily emails are hard to read in dark mode

### ISSUE THREAD

**Issue by philgyford** [philgyford/pepysdiary#477]
Text remains dark grey, for example.

**Comment by philgyford** [comment]
Done. For future reference, colours are like:

```css
.newsletter-body p,
.newsletter-body li,
.newsletter-body th, 
.newsletter-body td, 
.newsletter-body dt, 
.newsletter-body dd {
  color: #4a4a45;
}
.newsletter-body aside {
  border-top: 1px solid #dfdfd8;
  border-bottom: 1px solid #dfdfd8;
}
@media (prefers-color-scheme: dark) {
  .newsletter-body p,
  .newsletter-body li,
  .newsletter-body th, 
  .newsletter-body td, 
  .newsletter-body dt, 
  .newsletter-body dd {
    color: #eaeae5;
  }
  .newsletter-body aside {
    border-top-color: #5f5f58;
    border-bottom-color: #5f5f58;
  }
  .newsletter-container a {
    color: #aac3dd !important;
  }
}
```
